In [11]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

2023-11-25 12:10:39.660106: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-25 12:10:40.532666: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-25 12:10:40.532706: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-25 12:10:40.538234: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-25 12:10:41.002213: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-25 12:10:41.006448: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

In [12]:
from keras.applications.xception import preprocess_input

In [13]:
!ls

Dockerfile	   housing.csv		   ml-zoomcamp-hw-3.ipynb  test_w9.py
bees-wasps.h5	   lambda_function.py	   ml-zoomcamp-hw-4.ipynb  week-5
bees-wasps.tflite  ml-zoomcamp-hw-1.ipynb  ml-zoomcamp-hw-6.ipynb  week-8
data.csv	   ml-zoomcamp-hw-2.ipynb  ml-zoomcamp-hw-9.ipynb


In [14]:
model = keras.models.load_model('bees-wasps.h5')

2023-11-25 12:10:49.782930: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-11-25 12:10:50.020414: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 44859392 exceeds 10% of free system memory.
2023-11-25 12:10:50.079331: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 44859392 exceeds 10% of free system memory.
2023-11-25 12:10:50.103364: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 44859392 exceeds 10% of free system memory.
2023-11-25 12:10:50.709400: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 44859392 exceeds 10% of free system memory.
2023-11-25 12:10:50.912823: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 44859392 exceeds 10% of free system memory.


### Converting to Tf-Lite

In [15]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open('bees-wasps.tflite', 'wb') as f_out:
    f_out.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpk4ye4c3p/assets


INFO:tensorflow:Assets written to: /tmp/tmpk4ye4c3p/assets
2023-11-25 12:10:57.696325: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:378] Ignored output_format.
2023-11-25 12:10:57.696410: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:381] Ignored drop_control_dependency.
2023-11-25 12:10:57.703302: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpk4ye4c3p
2023-11-25 12:10:57.704488: I tensorflow/cc/saved_model/reader.cc:51] Reading meta graph with tags { serve }
2023-11-25 12:10:57.704514: I tensorflow/cc/saved_model/reader.cc:146] Reading SavedModel debug info (if present) from: /tmp/tmpk4ye4c3p
2023-11-25 12:10:57.709732: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-11-25 12:10:57.710748: I tensorflow/cc/saved_model/loader.cc:233] Restoring SavedModel bundle.
2023-11-25 12:10:58.394451: I tensorflow/cc/saved_model/loader.cc:217] Running initializatio

In [16]:
!ls -lh

total 132M
-rwxrwxrwx 1 abhijit abhijit  275 Nov 25 11:51 Dockerfile
-rwxrwxrwx 1 abhijit abhijit  86M Nov 18 03:21 bees-wasps.h5
-rwxrwxrwx 1 abhijit abhijit  43M Nov 25 12:11 bees-wasps.tflite
-rwxrwxrwx 1 abhijit abhijit 1.5M Nov 24 20:58 data.csv
-rwxrwxrwx 1 abhijit abhijit 1.4M Nov 24 20:58 housing.csv
-rwxrwxrwx 1 abhijit abhijit 1.5K Nov 25 12:01 lambda_function.py
-rwxrwxrwx 1 abhijit abhijit  19K Nov 24 20:58 ml-zoomcamp-hw-1.ipynb
-rwxrwxrwx 1 abhijit abhijit  60K Nov 24 20:58 ml-zoomcamp-hw-2.ipynb
-rwxrwxrwx 1 abhijit abhijit  68K Nov 24 20:58 ml-zoomcamp-hw-3.ipynb
-rwxrwxrwx 1 abhijit abhijit 100K Nov 24 20:58 ml-zoomcamp-hw-4.ipynb
-rwxrwxrwx 1 abhijit abhijit  72K Nov 24 20:58 ml-zoomcamp-hw-6.ipynb
-rwxrwxrwx 1 abhijit abhijit  20K Nov 25 12:10 ml-zoomcamp-hw-9.ipynb
-rwxrwxrwx 1 abhijit abhijit  240 Nov 25 12:00 test_w9.py
drwxrwxrwx 1 abhijit abhijit  512 Nov 24 20:58 week-5
drwxrwxrwx 1 abhijit abhijit  512 Nov 24 20:58 week-8


* The Tflite converted model is 43 Mb large

### Input and Output Indices

In [17]:
import tensorflow.lite as tflite

In [18]:
interpreter = tflite.Interpreter(model_path='bees-wasps.tflite')
interpreter.allocate_tensors()

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


In [19]:
input_index = interpreter.get_input_details()[0]['index']

In [20]:
output_index = interpreter.get_output_details()[0]['index']

In [21]:
output_index

13

### Preparing the Image

In [16]:
!pip install pillow

In [22]:
from io import BytesIO
from urllib import request

from PIL import Image

def download_image(url):
    with request.urlopen(url) as resp:
        buffer = resp.read()
    stream = BytesIO(buffer)
    img = Image.open(stream)
    return img


def prepare_image(img, target_size):
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = img.resize(target_size, Image.NEAREST)
    return img

In [23]:
url = 'https://habrastorage.org/webt/rt/d9/dh/rtd9dhsmhwrdezeldzoqgijdg8a.jpeg'
img = download_image(url)

In [26]:
prep_img = prepare_image(img, target_size=(150,150))

### Preprocessing

In [31]:
x = np.array(prep_img, dtype='float32')
# X = np.array([x])

In [32]:
x

array([[[241., 231., 219.],
        [239., 235., 249.],
        [233., 229., 244.],
        ...,
        [ 74.,  85.,  42.],
        [ 89., 104.,  39.],
        [ 76.,  92.,  30.]],

       [[242., 232., 222.],
        [234., 232., 245.],
        [230., 228., 242.],
        ...,
        [ 70.,  86.,  41.],
        [120., 129.,  48.],
        [115., 126.,  47.]],

       [[237., 225., 209.],
        [233., 232., 246.],
        [231., 228., 245.],
        ...,
        [ 82.,  96.,  45.],
        [129., 134.,  52.],
        [110., 119.,  52.]],

       ...,

       [[  8.,  17.,  12.],
        [  6.,  22.,  12.],
        [ 21.,  21.,  23.],
        ...,
        [113.,  92.,  13.],
        [ 43.,  45.,  31.],
        [ 32.,  40.,  29.]],

       [[  8.,  17.,  12.],
        [ 20.,  30.,  22.],
        [ 14.,  25.,  19.],
        ...,
        [ 82.,  68.,  19.],
        [ 31.,  34.,  27.],
        [ 24.,  29.,  23.]],

       [[  5.,  10.,   6.],
        [ 22.,  29.,  21.],
        [ 26.,  

In [33]:
def process_np(x):
    x /= 255.  # As numbers range from 0-255. Instead of using 127.5 we need 255 to tranform within 0-1
    return x

In [34]:
X = np.array([x])
X = process_np(X)

In [35]:
X.shape

(1, 150, 150, 3)

In [36]:
X[0].shape

(150, 150, 3)

In [37]:
X[0][:,:,0].shape

(150, 150)

In [38]:
X[0][:,:, 0][0]

array([0.94509804, 0.9372549 , 0.9137255 , 0.89411765, 0.89411765,
       0.8901961 , 0.8666667 , 0.8745098 , 0.8666667 , 0.85882354,
       0.84313726, 0.84313726, 0.84313726, 0.8392157 , 0.8235294 ,
       0.8235294 , 0.80784315, 0.8156863 , 0.80784315, 0.8       ,
       0.8       , 0.8039216 , 0.7921569 , 0.8       , 0.7921569 ,
       0.8       , 0.78039217, 0.78431374, 0.78431374, 0.78039217,
       0.78431374, 0.7764706 , 0.7607843 , 0.7607843 , 0.7529412 ,
       0.7529412 , 0.7490196 , 0.7490196 , 0.74509805, 0.7372549 ,
       0.73333335, 0.73333335, 0.7372549 , 0.7372549 , 0.73333335,
       0.7372549 , 0.7372549 , 0.73333335, 0.7294118 , 0.7294118 ,
       0.72156864, 0.7254902 , 0.7137255 , 0.70980394, 0.7058824 ,
       0.69411767, 0.69803923, 0.69411767, 0.6901961 , 0.6901961 ,
       0.69411767, 0.69411767, 0.68235296, 0.6784314 , 0.6784314 ,
       0.6745098 , 0.6745098 , 0.6745098 , 0.6784314 , 0.6666667 ,
       0.6666667 , 0.65882355, 0.654902  , 0.64705884, 0.64313

In [39]:
interpreter.set_tensor(input_index, X)
interpreter.invoke()

preds = interpreter.get_tensor(output_index)
preds

array([[0.65898407]], dtype=float32)

### Without Using Tensorflow

In [1]:
import numpy as np
import tflite_runtime.interpreter as tflite

from io import BytesIO
from urllib import request

from PIL import Image

In [2]:
interpreter = tflite.Interpreter(model_path='bees-wasps.tflite')
interpreter.allocate_tensors()

input_index = interpreter.get_input_details()[0]['index']
output_index = interpreter.get_output_details()[0]['index']

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


In [3]:


def download_image(url):
    with request.urlopen(url) as resp:
        buffer = resp.read()
    stream = BytesIO(buffer)
    img = Image.open(stream)
    return img


def prepare_image(img, target_size):
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = img.resize(target_size, Image.NEAREST)
    return img

def process_input(X):
    X /= 255.
    return X

In [4]:
url = 'https://habrastorage.org/webt/rt/d9/dh/rtd9dhsmhwrdezeldzoqgijdg8a.jpeg'

In [5]:
def preprocessor(url, target_size = (150, 150)):
    img = download_image(url)
    img = prepare_image(img, target_size)
    
    # Convert to numpy array
    x = np.array(img, dtype='float32')
    X = np.array([x])
    X = process_input(X)
    
    return X

In [6]:
X = preprocessor(url)

In [7]:
X.shape

(1, 150, 150, 3)

In [8]:
X[0, 0, 0, :]

array([0.94509804, 0.90588236, 0.85882354], dtype=float32)

In [9]:
interpreter.set_tensor(input_index, X)
interpreter.invoke()

preds = interpreter.get_tensor(output_index)

In [10]:
preds[0]

array([0.65898407], dtype=float32)